kind: Service                             
apiVersion: v1
metadata:
  name: mrakash
  labels:
    app: mrakash
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      #nodePort: 31200
  selector:
    app: mrakash                    
  type: LoadBalancer 
